#pragma once
// Build-time defaults are generated by scripts/build.sh.
#if __has_include("wifi_defaults.h")
#include "wifi_defaults.h"
#else
constexpr char DEFAULT_SSID[] = "";
constexpr char DEFAULT_PASSWORD[] = "";
#endif
constexpr char SERVICE_UUID[] = "98bf0001-7d56-4f36-913a-2f0743a89c11";
constexpr char WRITE_UUID[] = "98bf0002-7d56-4f36-913a-2f0743a89c11";
constexpr char STATUS_UUID[] = "98bf0003-7d56-4f36-913a-2f0743a89c11";
constexpr unsigned long WIFI_TIMEOUT_MS = 20000;
