"""Generate an ignored C++ header from build-time environment variables."""
import os
from pathlib import Path
import sys


def credentials(env):
    ssid = env.get("RLCD_WIFI_SSID", "")
    password = env.get("RLCD_WIFI_PASSWORD", "")
    if "\0" in ssid or "\0" in password:
        raise ValueError("Wi-Fi parameters must not contain NUL")
    if len(ssid.encode("utf-8")) > 32:
        raise ValueError("RLCD_WIFI_SSID must be at most 32 UTF-8 bytes")
    if password and not ssid:
        raise ValueError("RLCD_WIFI_PASSWORD requires RLCD_WIFI_SSID")
    size = len(password.encode("utf-8"))
    if size and not (8 <= size <= 63 or
                     (size == 64 and all(c in "0123456789abcdefABCDEF" for c in password))):
        raise ValueError("Wi-Fi password must be empty, 8-63 UTF-8 bytes, or 64 hex digits")
    return ssid, password


def literal(value):
    return '"' + ''.join(f"\\x{byte:02x}" for byte in value.encode("utf-8")) + '"'


def main():
    target = Path(sys.argv[1])
    # Remove stale credentials even if validation fails.
    target.unlink(missing_ok=True)
    try:
        ssid, password = credentials(os.environ)
    except ValueError as error:
        raise SystemExit(str(error)) from None
    target.write_text(
        "#pragma once\n// Generated by scripts/build.sh; do not commit.\n"
        f"constexpr char DEFAULT_SSID[] = {literal(ssid)};\n"
        f"constexpr char DEFAULT_PASSWORD[] = {literal(password)};\n",
        encoding="utf-8",
    )
    target.chmod(0o600)


if __name__ == "__main__":
    main()
